name: leilao_veiculos
services:
  postgres:
    container_name: leilao_veiculos_pg
    image: postgres:16.0-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
