DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_USUARIO;
CREATE TABLE LEILAO_VEICULOS.TB_USUARIO (
    ID_USUARIO BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE VARCHAR(50),
    DOCUMENTO VARCHAR(100) UNIQUE NOT NULL,
    NOME_FANTASIA VARCHAR(100),
    CONTA_BANCARIA VARCHAR(100),
    INTERESSE VARCHAR(150),
    DATA_NASCIMENTO VARCHAR(15),
    PAPEL VARCHAR(30) NOT NULL,
    DH_CRIACAO TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_NOTIFICACAO;
CREATE TABLE LEILAO_VEICULOS.TB_NOTIFICACAO (
    ID_NOTIFICACAO BIGSERIAL PRIMARY KEY,
    ID_USUARIO REFERENCES LEILAO_VEICULOS.TB_USUARIO (ID_USUARIO),
    CONTEUDO VARCHAR(255) NOT NULL,
    IN_VISUALIZADO BOOLEAN NOT NULL,
    DH_CRIACAO TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_VEICULO;
CREATE TABLE LEILAO_VEICULOS.TB_VEICULO (
    ID_VEICULO BIGSERIAL PRIMARY KEY,
    MODELO VARCHAR(100) NOT NULL,
    DH_CRIACAO TIMESTAMP NOT NULL,
    PLACA VARCHAR(10) NOT NULL,
    RENAVAM VARCHAR(20) NOT NULL,
    COR VARCHAR(20) NOT NULL,
    QUILOMETRAGEM INT NOT NULL,
    DESCRICAO VARCHAR(255),
    TIPO_VEICULO VARCHAR(50) NOT NULL,
    CILINDRADA INT, -- Specific to Moto
    MARCHA INT, -- Specific to Moto
    PARTIDA VARCHAR(50), -- Specific to Moto
    NUMERO_PORTAS INT, -- Specific to Carro
    DIRECAO VARCHAR(50), -- Specific to Carro
    CAMBIO VARCHAR(50) -- Specific to Carro
);
