CREATE SCHEMA IF NOT EXISTS LEILAO_VEICULOS;

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_USUARIO CASCADE;
CREATE TABLE LEILAO_VEICULOS.TB_USUARIO (
  ID_USUARIO BIGSERIAL PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  SOBRENOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  TELEFONE VARCHAR(50),
  DOCUMENTO VARCHAR(100) UNIQUE NOT NULL,
  NOME_FANTASIA VARCHAR(100),
  CONTA_BANCARIA VARCHAR(100),
  INTERESSE VARCHAR(150),
  DATA_NASCIMENTO VARCHAR(15),
  PAPEL VARCHAR(30) NOT NULL,
  DH_CRIACAO TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_NOTIFICACAO;
CREATE TABLE LEILAO_VEICULOS.TB_NOTIFICACAO (
  ID_NOTIFICACAO BIGSERIAL PRIMARY KEY,
  ID_USUARIO BIGINT REFERENCES LEILAO_VEICULOS.TB_USUARIO (ID_USUARIO),
  CONTEUDO VARCHAR(255) NOT NULL,
  IS_VISUALIZADO BOOLEAN NOT NULL,
  DH_CRIACAO TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_VEICULO CASCADE;
CREATE TABLE LEILAO_VEICULOS.TB_VEICULO (
  ID_VEICULO BIGSERIAL PRIMARY KEY,
  MODELO VARCHAR(100) NOT NULL,
  DH_CRIACAO TIMESTAMP NOT NULL,
  PLACA VARCHAR(10) NOT NULL,
  RENAVAM VARCHAR(20) NOT NULL,
  COR VARCHAR(20) NOT NULL,
  QUILOMETRAGEM INT NOT NULL,
  DESCRICAO VARCHAR(255),
  TIPO_VEICULO VARCHAR(50) NOT NULL,
  CILINDRADA INT,
  MARCHA INT,
  PARTIDA VARCHAR(50),
  NUMERO_PORTAS INT,
  DIRECAO VARCHAR(50),
  CAMBIO VARCHAR(50)
);

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_OFERTA CASCADE;
CREATE TABLE LEILAO_VEICULOS.TB_OFERTA (
  ID_OFERTA BIGSERIAL PRIMARY KEY,
  DH_CRIACAO TIMESTAMP NOT NULL,
  DH_INICIO TIMESTAMP NOT NULL,
  DH_FIM TIMESTAMP NOT NULL,
  ID_VEICULO BIGINT REFERENCES LEILAO_VEICULOS.TB_VEICULO (ID_VEICULO),
  ID_USUARIO BIGINT REFERENCES LEILAO_VEICULOS.TB_USUARIO (ID_USUARIO),
  VALOR_INICIAL NUMERIC(10, 2),
  VALOR_INCREMENTAL NUMERIC(10, 2),
  ESTADO VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_ENDERECO;
CREATE TABLE LEILAO_VEICULOS.TB_ENDERECO (
  ID_ENDERECO BIGSERIAL PRIMARY KEY,
  ID_OFERTA BIGINT REFERENCES LEILAO_VEICULOS.TB_OFERTA (ID_OFERTA),
  ESTADO VARCHAR(2) NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  CEP VARCHAR(9) NOT NULL,
  BAIRRO VARCHAR(100) NOT NULL,
  RUA VARCHAR(150) NOT NULL,
  NUMERO VARCHAR(15) NOT NULL,
  DH_CRIACAO TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_LANCE;
CREATE TABLE LEILAO_VEICULOS.TB_LANCE (
  ID_LANCE BIGSERIAL PRIMARY KEY,
  ID_OFERTA BIGINT REFERENCES LEILAO_VEICULOS.TB_OFERTA (ID_OFERTA),
  ID_USUARIO BIGINT REFERENCES LEILAO_VEICULOS.TB_USUARIO (ID_USUARIO),
  VALOR NUMERIC(10, 2),
  DH_CRIACAO TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_DIVULGACAO;
CREATE TABLE LEILAO_VEICULOS.TB_DIVULGACAO (
	UID_DIVULGACAO VARCHAR NOT NULL,
	TX_NOME VARCHAR NOT NULL,
	TX_LINK VARCHAR NOT NULL,
	DH_CRIACAO TIMESTAMP NOT NULL
);