DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_USUARIO;
CREATE TABLE LEILAO_VEICULOS.TB_USUARIO (
    ID_USUARIO BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE VARCHAR(50),
    DOCUMENTO VARCHAR(100) UNIQUE NOT NULL,
    NOME_FANTASIA VARCHAR(100),
    CONTA_BANCARIA VARCHAR(100),
    INTERESSE VARCHAR(150),
    DATA_NASCIMENTO VARCHAR(15),
    PAPEL VARCHAR(30) NOT NULL,
    DH_CRIACAO TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS LEILAO_VEICULOS.TB_NOTIFICACAO;
CREATE TABLE LEILAO_VEICULOS.TB_NOTIFICACAO (
    ID_NOTIFICACAO BIGSERIAL PRIMARY KEY,
    ID_USUARIO REFERENCES LEILAO_VEICULOS.TB_USUARIO (ID_USUARIO),
    CONTEUDO VARCHAR(255) NOT NULL,
    IN_VISUALIZADO BOOLEAN NOT NULL,
    DH_CRIACAO TIMESTAMP NOT NULL
);